// <auto-generated />
namespace Raya.Employee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addconfirmtoemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addconfirmtoemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202206041338110_addconfirmtoemployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
